
logging:
  level:
    root: INFO

management:
  context-path: /actuator
  security:
    enabled: true
  endpoints:
    web:
      exposure:
        include: 'health'

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 10000

okhttp:
  enabled: true


spring:
  datasource:
    url: jdbc:h2:mem:hexdb
    username: sa
    password:
    platform: h2
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
client:
  my-service:
    config:
      url: 'http://localhost:8080'
      endpoint:
        health: '/actuator/health'